language: python
python:
    - "2.7"
    - "3.4"
    - "pypy"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
install:
    - pip install django==$DJANGO_VERSION
    - pip install -r requirements/ci.txt --use-mirrors
    
services:
    - redis-server
    - memcached
script: python manage.py test --with-cov
after_success:
    - coveralls
